### ISSUE TITLE
incorrect metadata for WCDT rnaseq

### ISSUE THREAD

**Issue by chkw** [DataBiosphere/cgp-dashboard#12]
I have found some data files in Redwood that seem to be incorrectly labelled as WXS data. I’m not sure how this happened. It seems the `Submitter Experimental Design` should be something like `rnaseq`. I’ll include a file attachment here that has the erroneous entries.
[manifest_dev_20170327_mislabeled_wxs.txt](https://github.com/BD2KGenomics/dcc-dashboard/files/873677/manifest_dev_20170327_mislabeled_wxs.txt)

Similarly, I have found data that seems incorrectly labeled as rnaseq when it should be WXS. The following file attachment contains the erroneous entries.
[manifest_dev_20170327_mislabeled_rnaseq.txt](https://github.com/BD2KGenomics/dcc-dashboard/files/873731/manifest_dev_20170327_mislabeled_rnaseq.txt)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-7)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-7

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

We no longer are hosting this data
