### ISSUE TITLE
File Browser suggestions/wishlist

### ISSUE THREAD

**Issue by klearned** [DataBiosphere/cgp-dashboard#29]
Katrina's File Browser suggestions/wishlist

0. Search box to search a specimen id or donor id or filename or uuid.

1. Ability to adjust the number of files displayed on a single page (including see all?)

Personally, I really want to see more files on each page, and quite often, I want to see all the files from my selection on one page. I realize this might not be what everyone would want though so, perhaps letting people choose how many they want to see per page would be good: 5, 10, 20, 50, 100, all files at once. Since I am looking at pairs of files a lot, even if you changed from only seeing 5 (an odd number) to seeing 6 (an even number) on a page, I'd be happier!

2. Ability to deselect (and then reselect) individual files from being included in the Download Manifest. 

3. File Size column

4. Date Created column

5. Ability to minimize the facet panel (to make more room to see resulting files)

6. Hide/Unhide columns

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-10)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-10

**Comment by klearned** [comment]
@caaespin @wshands @kozbo

**Comment by klearned** [comment]
Just updated the above list with:

0. Search box to search a specimen id or donor id or filename or uuid.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

The number of items being displayed is now customizable.

You can now search by donor it and file id.

File size is also displayed.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Going to close this ticket; the things we might address are covered under BOARD‌-80 and AZUL‌-358.
