### ISSUE TITLE
Add Scoping information on the help page

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/cgp-dashboard#30]
The help page needs to be updated to account for token scoping and how it relates to the manifest file (i.e. it should explain what `program` does)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-1)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-1

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

There is no Help page any more; this is not applicable.
