### ISSUE TITLE
New Section with changes

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/cgp-dashboard#6]
Adding new section to dashboard which includes the changes on the browser.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-6)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-6

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Not sure what this means; maybe it’s a footer. Going to close.
