### ISSUE TITLE
Show Index Status

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/cgp-dashboard#9]
Show the last time the index was updated, as well as when the page was loaded.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-5)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-5

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Now the index is progressively updated, so no longer applicable.
